# Generated by Django 2.2.1 on 2019-08-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_name',
            field=models.CharField(default='Titanic', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
