# Generated by Django 2.2.1 on 2019-08-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190810_0033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Source',
        ),
    ]
