language: python
python:
  - 3.5
  - 3.6
  - 3.7
dist: xenial
env:
  - PARALLELIZE=true
before_install:
  - pip install -U pip
  - pip install codecov
  - pip install -U pip setuptools
install:
  - pip install -r requirements.txt
  - python -m textblob.download_corpora
  - python -c 'import nltk; nltk.download("stopwords")' # install package + test dependencies
script: python -m unittest discover pyautoml/ # run tests
after_success:
  - codecov # submit coverage
